version: '3.2'
services:
  mongo-primary:
    image: mongo:4.1.13-bionic
    command: --replSet rs0 --bind_ip_all
    networks:
      - mongo-cluster
  mongo-secondary:
    image: mongo:4.1.13-bionic
    command: --replSet rs0 --bind_ip_all
    networks:
      - mongo-cluster
    depends_on:
      - mongo-primary
  mongo-third:
    image: mongo:4.1.13-bionic
    command: --replSet rs0 --bind_ip_all
    networks:
      - mongo-cluster
    depends_on:
      - mongo-primary
  mongo-seeder:
    build: ./mongo-seeder
    networks:
      - mongo-cluster
    depends_on:
      - mongo-primary
      - mongo-secondary
      - mongo-third
networks:
  mongo-cluster:
    driver: bridge